# This is a basic workflow to help you get started with Actions
name: Checkmarx_Scans

# Controls when the action will run. 
on:
  push:
    # Sequence of patterns matched against refs/heads
    tags:        
      - v\d+.*             # Push events to v1 tag
      - V\d+.*            # Push events to v1.0, v1.1, and v1.9 tags

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      - uses: actions/checkout@v1
      - name: Get result
        run: ${{ secrets.CHECKMARX_SCAN_APPNODEJS }}
